var friendage=[20,30,40,50];
console.log(friendage);
console.log(friendage[1]);
var shafi=friendage[2];
console.log(shafi);
friendage[3]=45;
console.log(friendage);
friendage[4]=50;
console.log(friendage.length);
var position=friendage.indexOf(30);
console.log(position);
friendage.push(60);
console.log(friendage);
friendage.shift();
console.log(friendage);
friendage.unshift(100);
console.log(friendage);
friendage.splice(1,1);
console.log(friendage);
friendage[2]=50;
console.log(friendage);
